// license:BSD-3-Clause
// copyright-holders:Wilbert Pol
/**********************************************************************

    TI Explorer NuBus Peripheral Interface (NUPI) board.

Board references found:
- 2238040
- 2243146

The manual only documents the NuBus-facing side, some locations in the
shared RAM.

There is no schematic available, the implementation is purely based on
investigation of the mc68000 firmware.

The NUPI interfaced with storage units through SCSI. There were three
types of enclosures housing the actual disk/tape drives:
- Mass Storage Unit holding 2 disks or 1 disk and a 1/4-inch tape drive.
  The 1/4-inch tape drive is a unit consisting of a tape formatter (Emulex
  MT01 / MT0151001) and a tape drive (Cipher Data Products series 540 or
  Archive Viper 2060S/2125S).
- 1/2-inch tape enclosure (Cipher Data MT3201 / CacheTape).
- Trimline disk cabinet for large SMD disks. Unknown if this could
  communicate with the NUPI or whether it required a SMC.


The two fault LEDs, and why they are the flag register:

Documentation section 3.2 and appendix C: "The NUPI has red and yellow LEDs.
The red LED indicates a NUPI board fault; the yellow LED indicates a SCSI bus
fault." Both are lit at power-up, which section 3.3 turns into a service
instruction - "check that the red LED on each of the circuit boards in the
enclosure is on to indicate that the self-test for that board is operating".

Unlike every other board in this machine, nothing on the NuBus side drives
them: appendix C is a list of the conditions under which *the NUPI firmware*
sets them, and each one of its causes is a write by the 68000 to one of the
three flag latches at $801a2/$801ac/$801ae (see mpu_map()). So the LEDs are
modelled as two bits of the NuBus-visible flag register, and the existing
latch handlers are the whole implementation:

  red    = flag register bit 1, "self-test passed", 0 = passed
  yellow = flag register bit 2, "SCSI passed", 0 = passed

That the lamp and the flag bit are one and the same latch is an inference, but
a well-cornered one: there are exactly three latch addresses for exactly three
flag bits, the two conditions the lamps report are two of those bits, and every
firmware site writes its latch alone, never paired with a second address a
separate lamp register would need.

Appendix C's causes map onto firmware sites one for one, and all of them
therefore already work. Red: self-test failure ($801a2 at ROM 0x1da, a seq
per dispatcher entry), bus test failure (0x200e), 68000 hardware error trap
(0x375e/0x37a2/0x37b8 - the bus-error, address-error and illegal-instruction
vectors, all funnelling into the error reporter at 0x37d6 whose last act is
sf $801a2), software error trap (same reporter), and the operating system
setting configuration register bit 2. Yellow: the SCSI self-test ($801ac at
0x6fc and 0x7d6) and the NCR5385 interrupt paths. The catastrophic-failure
halt at 0x264 sf's both latches and then stop #$2500, which is the "remains
on, replace the board" case of section 3.3.

Configuration register bit 2 reaches the red LED through the firmware, not
through hardware: the IRQ5 handler reads the register at ROM 0xb58 and does
seq $801a2 on bit 2 (0xb6a), so setting the bit lights the lamp and clearing
it releases the lamp to whatever the seq now computes. Section 5.3.2 documents
exactly that - "a configuration register update operation sets (or resets)
this bit to reflect the condition of the configuration register's fault LED
bit" - and it is what Field Maintenance table 1-1 step 7 sees as the red LED
blinking on and off during the NuBus test.

TODO:
- Section 3.2: "either a self-test failure or an active test-LED bit in the
  configuration register prohibits the NUPI from processing any commands",
  subject to the configuration register's failure override bit (bit 8). The
  firmware presumably enforces this from the same latch state; nothing here
  models it, and no boot path exercises it.


The 68000 code structure, concretely:

Interrupts:
irq1 - DMAINT - dma complete interrupt
irq2 - SCSIINT - SCSI interrupt
irq3 - TIMERINT - Timer interrupt
irq4 - NUINT2 - Nubus interrupt 2. When nubus error
irq5 - NUINT3 - Nubus interrupt 1. Generated by writing command_address.

5 1/4 inch 143MB Winchester drives
- average access time 27 msec
- transfer rate 5mbit/s
60 megabyte cartridge tapes

The SCSI targets are mass storage units, not the drives themselves: one NUPI
interface carries several units and each unit carries up to two devices,
which the firmware selects by LUN - sent both in the IDENTIFY message and,
redundantly, in CDB byte 1 bits 7:5. That is what explorer_msu.cpp models,
two LUNs per unit; device_add_mconfig() puts one at SCSI ID 0 and one at
SCSI ID 2, matching the dumped disks - two drives behind the first unit and
one behind the second. The board itself is initiator 5 (not 7 - see the
own-ID compare in self-test entry 6).

TODO:
- Cartridge tape devices are not emulated. A unit's two devices may be
  1/4 inch cartridge tapes behind an Emulex MT01 Tape Controller rather
  than Winchesters, and explorer_msu.cpp implements the disk command set
  only.
  The 1/2 inch tape enclosure is a separate SCSI target and is emulated,
  see mt3201.cpp.

- Whether an Adaptec SCSI interface sits between the formatter and the
  Winchester drives is unconfirmed; the only evidence is that the
  documentation for the disk formatter mentions 'adaptec'. The manual that
  would settle it, Explorer Winchester Disk Formatter (Adaptec) Supplement
  2243149-0001, is not among the scanned manuals available here. This only
  matters if the formatter ever has to be modelled at chip level rather than
  by its command set.

**********************************************************************/

#include "emu.h"
#include "explorer_nupi.h"

#include "explorer_msu.h"
#include "mt3201.h"

#define LOG_MISC (1U << 1)
#define LOG_DMA (1U << 2)
#define LOG_CMD (1U << 3)
#define LOG_NUBUS (1U << 4)
#define LOG_RAM_WINDOW (1U << 5)

//#define VERBOSE (0)
#define VERBOSE (LOG_MISC | LOG_DMA | LOG_CMD)
#include "logmacro.h"


DEFINE_DEVICE_TYPE(NUPI, explorer_nupi_device, "explorer_nupi", "TI NuBus Peripheral Interface (2243146-0001B)")

namespace {

void nupi_scsi_devices(device_slot_interface &device)
{
	device.option_add("msu", EXPLORER_MSU);
	device.option_add("mt3201", MT3201);
}

constexpr u16 UNKNOWN_800C04_SEQUENCE[] = { 0xeb34, 0xeb38 };

// Flag register (>Fs'D40002), doc section 5.3.4 and figure 5-3. Every bit is
// documented "active (low)", so a set bit is the bad case in each of the three,
// and all three come up set - see device_reset(). Bits 3-7 are reserved and
// always read 0.
constexpr u8 FLAG_SELF_TEST_COMPLETE = 0x01;
constexpr u8 FLAG_SELF_TEST_PASSED = 0x02; // also the red board fault LED
constexpr u8 FLAG_SCSI_PASSED = 0x04;      // also the yellow SCSI bus fault LED
constexpr u8 FLAG_POWER_UP = FLAG_SELF_TEST_COMPLETE | FLAG_SELF_TEST_PASSED | FLAG_SCSI_PASSED;

} // anonymous namespace


explorer_nupi_device::explorer_nupi_device(const machine_config &mconfig, const char *tag, device_t *owner, u32 clock) :
	device_t(mconfig, NUPI, tag, owner, clock),
	device_ti_nubus_card_interface(mconfig, *this),
	m_mpu(*this, "mpu"),
	m_scsi(*this, "scsi"),
	m_scsibus(*this, "scsibus"),
	m_ram(*this, "ram"),
	m_firmware(*this, "firmware"),
	m_firmware_nubus(*this, "firmware_nubus"),
	m_fault_led(*this, "fault_led"),
	m_scsi_led(*this, "scsi_led"),
	m_timer(nullptr),
	m_interval_timer(nullptr),
	m_dma_drain_timer(nullptr),
	m_flag_register(FLAG_POWER_UP),
	m_dma_address(0),
	m_dma_count(0)
{
}


void explorer_nupi_device::device_start()
{
	nubus().install_map(*this, &explorer_nupi_device::nubus_map);

	m_timer = timer_alloc(FUNC(explorer_nupi_device::timer_tick), this);
	m_timer->adjust(attotime::from_hz(60), 0, attotime::from_hz(60));

	m_interval_timer = timer_alloc(FUNC(explorer_nupi_device::interval_timer_expired), this);
	m_dma_drain_timer = timer_alloc(FUNC(explorer_nupi_device::dma_drain_timer_expired), this);

	{
		u8 const *const src = m_firmware->base();
		u8 *const dest = m_firmware_nubus->base();
		for (int i = 0; i < 0x4000; i++)
			dest[i] = src[i ^ 2];
	}

	save_item(NAME(m_flag_register));
	save_item(NAME(m_dma_address));
	save_item(NAME(m_dma_count));
	save_item(NAME(m_page_register));
	save_item(NAME(m_unknown_100001));
	save_item(NAME(m_unknown_100005));
	save_item(NAME(m_unknown_280000));
	save_item(NAME(m_unknown_518000));
	save_item(NAME(m_unknown_dma_801c00));
	save_item(NAME(m_unknown_dma_801c02));
	save_item(NAME(m_unknown_dma_803c00));
	save_item(NAME(m_dma_address_lo_fresh));
	save_item(NAME(m_dma_address_lo_negate_next));
	save_item(NAME(m_dma_address_lo_raw));
	save_item(NAME(m_dma_address_hi_raw));
	save_item(NAME(m_dma_address_loaded));
	save_item(NAME(m_dma_direction));
	save_item(NAME(m_fifo_out_pos));
	save_item(NAME(m_dma_irq5_enabled));
	save_item(NAME(m_unknown_800c04_toggle));
	save_item(NAME(m_unknown_280001));
	save_item(NAME(m_unknown_280001_bits12_toggle));
	save_item(NAME(m_unknown_300000));
	save_item(NAME(m_unknown_300001));
	save_item(NAME(m_interval_timer_regs));
	save_item(NAME(m_fifo));
	save_item(NAME(m_unknown_450000_holding));
	save_item(NAME(m_fifo_in_pos));
	save_item(NAME(m_unknown_450000_byte_phase));
	save_item(NAME(m_scsi_fifo_pending_byte));
	save_item(NAME(m_scsi_fifo_have_pending_byte));
	save_item(NAME(m_scsi_fifo_pending_word));
	save_item(NAME(m_scsi_fifo_have_pending_word));
	save_item(NAME(m_dma_mode));
	save_item(NAME(m_fifo_drain_pos));
	save_item(NAME(m_dma_target_configured));
	save_item(NAME(m_dma_in_flight));
	save_item(NAME(m_dma_out_byte_phase));
	save_item(NAME(m_dma_transfer_start_pos));
	save_item(NAME(m_dma_transfer_start_pending));
	save_item(NAME(m_dma_count_pending_byte));
	save_item(NAME(m_dma_count_have_pending_byte));
}


void explorer_nupi_device::device_reset()
{
	m_flag_register = FLAG_POWER_UP;
	update_leds();

	m_dma_address = 0;
	m_dma_count = 0;
	m_unknown_100001 = 0;
	m_unknown_100005 = 0;
	m_unknown_280000 = 0;
	m_unknown_518000 = 0;
	m_unknown_dma_801c00 = 0;
	m_unknown_dma_801c02 = 0;
	m_unknown_dma_803c00 = 0;
	m_dma_address_lo_fresh = true;
	m_dma_address_lo_negate_next = false;
	m_dma_address_lo_raw = 0;
	m_dma_address_hi_raw = 0;
	m_dma_address_loaded = false;
	m_dma_direction = 0;
	m_fifo_out_pos = 0;
	m_dma_irq5_enabled = false;
	m_unknown_800c04_toggle = 0;
	m_unknown_280001 = 0x01;
	m_unknown_280001_bits12_toggle = false;
	m_unknown_300000 = 0;
	m_unknown_300001 = 0x0c;
	m_page_register = 0;
	std::fill(std::begin(m_interval_timer_regs), std::end(m_interval_timer_regs), 0);
	for (u16 &entry : m_fifo)
		entry = 0;
	m_unknown_450000_holding = 0;
	m_fifo_in_pos = 0;
	m_scsi_fifo_pending_byte = 0;
	m_scsi_fifo_have_pending_byte = false;
	m_scsi_fifo_pending_word = 0;
	m_scsi_fifo_have_pending_word = false;
	m_dma_mode = DMA_IDLE;
	m_fifo_drain_pos = 0;
	m_dma_target_configured = false;
	m_dma_in_flight = false;
	m_dma_out_byte_phase = 0;
	m_dma_transfer_start_pos = 0;
	m_dma_transfer_start_pending = true;
	m_dma_count_pending_byte = 0;
	m_dma_count_have_pending_byte = false;
	m_unknown_450000_byte_phase = 0;
}

TIMER_CALLBACK_MEMBER(explorer_nupi_device::timer_tick)
{
	m_mpu->set_input_line(M68K_IRQ_4, ASSERT_LINE);
	m_mpu->set_input_line(M68K_IRQ_4, CLEAR_LINE);
}

TIMER_CALLBACK_MEMBER(explorer_nupi_device::interval_timer_expired)
{
	m_mpu->set_input_line(M68K_IRQ_3, ASSERT_LINE);
}

// The input address counter is 12 bits and the self-test compares it raw, but the
// FIFO behind it is 2048 words.
void explorer_nupi_device::fifo_push(u16 word)
{
	m_fifo[m_fifo_in_pos & 0x7ff] = word;
	m_fifo_in_pos = (m_fifo_in_pos + 1) & 0x0fff;
}

TIMER_CALLBACK_MEMBER(explorer_nupi_device::dma_drain_timer_expired)
{
	if (m_dma_mode == DMA_FIFO_TO_NUBUS && m_fifo_drain_pos == (m_fifo_in_pos & 0x7ff))
		return;

	u16 const word = m_fifo[m_fifo_drain_pos];
	m_fifo_drain_pos = (m_fifo_drain_pos + 1) & 0x7ff;
	push_fifo_word_to_nubus(word);

	dma_drain_kick();
}

void explorer_nupi_device::dma_drain_kick()
{
	if (dma_draining() && !m_dma_drain_timer->enabled())
		m_dma_drain_timer->adjust(m_dma_mode == DMA_FIFO_TO_NUBUS ? attotime::from_usec(1) : attotime::from_usec(4));
}


u16 explorer_nupi_device::onboard_read16(u32 addr)
{
	u32 const local = (addr & 0x20000) ? (0x040000 | (addr & 0x3fff)) : (0x180000 | (addr & 0x0fff));
	return m_mpu->space(AS_PROGRAM).read_word(local);
}


void explorer_nupi_device::onboard_write16(u32 addr, u16 data)
{
	if (addr & 0x20000)
		return; // ROM - a transfer into it moves nothing
	m_mpu->space(AS_PROGRAM).write_word(0x180000 | (addr & 0x0fff), data);
}


void explorer_nupi_device::onboard_dma_run(bool host_group_read)
{
	if (m_dma_mode != DMA_ONBOARD)
		return;

	// Direction ($801a8) and width ($801d0 bit 15) are read live; the transfer walks the
	// address ($801c0, bits 17:2) and the count down as it goes.
	bool const to_fifo = m_dma_direction != 0;
	bool const is_16bit = BIT(m_dma_address_hi_raw, 15);

	while (m_dma_count)
	{
		// Outbound 16-bit hands the group's other half to the host port, so the
		// transfer only steps once $450000 has taken one.
		if (!to_fifo && is_16bit)
		{
			if (!host_group_read)
				return;
			host_group_read = false;
		}

		u32 const addr = u32(m_dma_address_lo_raw) << 2;
		if (to_fifo)
		{
			// Fills are always 16-bit: only the halfword at +0 is real, and it fills
			// both halves of the FIFO group (nothing else is driving the other half).
			u16 const word = onboard_read16(addr);
			fifo_push(word);
			fifo_push(word);
		}
		else
		{
			u16 const first = m_fifo[m_fifo_out_pos];
			m_fifo_out_pos = (m_fifo_out_pos + 1) & 0x7ff;
			if (is_16bit)
			{
				// The host port takes the group's other half.
				onboard_write16(addr, first);
			}
			else
			{
				u16 const second = m_fifo[m_fifo_out_pos];
				m_fifo_out_pos = (m_fifo_out_pos + 1) & 0x7ff;
				onboard_write16(addr + 2, first);
				onboard_write16(addr, second);
			}
		}

		m_dma_address_lo_raw++;
		m_dma_count--;
	}

	// Completion also raises IRQ5 when $3801ea enabled it.
	if (m_dma_irq5_enabled)
	{
		m_dma_irq5_enabled = false;
		m_mpu->set_input_line(M68K_IRQ_5, ASSERT_LINE);
	}
	dma_transfer_complete();
}


void explorer_nupi_device::dma_transfer_complete()
{
	m_mpu->set_input_line(M68K_IRQ_1, ASSERT_LINE);

	m_dma_mode = DMA_IDLE;

	m_unknown_100001 = 0;

	m_unknown_450000_holding = m_unknown_dma_803c00;

	m_dma_transfer_start_pending = true;
}


//**************************************************************************
//  NuBus-facing (host) registers - Section 5.3 of the NUPI General Description
//**************************************************************************

void explorer_nupi_device::nubus_map(address_map &map)
{
	map.unmap_value_high();

	map(0x00aa8000, 0x00aa801f).m(m_scsi, FUNC(ncr5385_device::map)).umask16(0x00ff);

	map(0x00d40002, 0x00d40002).r(FUNC(explorer_nupi_device::flag_register_r));

	map(0x00e00000, 0x00e00fff).rw(FUNC(explorer_nupi_device::ram_window_r), FUNC(explorer_nupi_device::ram_window_w));

	map(0x00ffc000, 0x00ffffff).r(FUNC(explorer_nupi_device::rom_r));
}


u32 explorer_nupi_device::ram_window_r(offs_t offset)
{
	return (u32(m_ram[offset * 2]) << 16) | m_ram[offset * 2 + 1];
}


void explorer_nupi_device::ram_window_w(offs_t offset, u32 data, u32 mem_mask)
{
	LOGMASKED(LOG_RAM_WINDOW, "%s: ram_window_w addr=%06x data=%08x mask=%08x\n", machine().describe_context(), 0xe00000 + offset * 4, data, mem_mask);

	u32 val = (u32(m_ram[offset * 2]) << 16) | m_ram[offset * 2 + 1];
	COMBINE_DATA(&val);
	m_ram[offset * 2] = val >> 16;
	m_ram[offset * 2 + 1] = val & 0xffff;

	if (mem_mask & 0xff000000)
	{
		if ((VERBOSE & LOG_CMD) && offset == 1)
		{
			u32 const cmd_addr = val;
			u32 const word0 = nubus().space().read_dword(cmd_addr);
			u32 const buffer_ptr = nubus().space().read_dword(cmd_addr + 0x08);
			u32 const word_count = nubus().space().read_dword(cmd_addr + 0x0c);
			u32 const block_addr = nubus().space().read_dword(cmd_addr + 0x10);
			u32 const event_addr = nubus().space().read_dword(cmd_addr + 0x14);
			LOGMASKED(LOG_CMD, "CMDLOG cmd_addr=%08X word0=%08X cmd=%02X unit=%02X (fmt=%d dev=%d) nupi_dst_bit=%d formatter_bit=%d buffer_ptr=%08X word_count=%08X block_addr=%08X event_addr=%08X\n",
				cmd_addr, word0, (word0 >> 24) & 0x3f, word0 & 0xff, (word0 >> 3) & 0x7, word0 & 0x1,
				BIT(word0, 31), BIT(word0, 30),
				buffer_ptr, word_count, block_addr, event_addr);
		}

		m_unknown_280000 = 0x30 | (offset & 3);
		m_mpu->set_input_line(M68K_IRQ_5, ASSERT_LINE);
	}
}


u8 explorer_nupi_device::unknown_280001_r()
{
	u8 const data = m_unknown_280001 ^ (m_unknown_280001_bits12_toggle ? 0x06 : 0x00);
	return data;
}


u8 explorer_nupi_device::flag_register_r()
{
	return m_flag_register;
}


void explorer_nupi_device::update_leds()
{
	m_fault_led = bool(m_flag_register & FLAG_SELF_TEST_PASSED);
	m_scsi_led = bool(m_flag_register & FLAG_SCSI_PASSED);
}


u8 explorer_nupi_device::rom_r(offs_t offset)
{
	return m_firmware_nubus->base()[offset & 0x3fff];
}


//**************************************************************************
//  MPU-side (internal) hardware
//**************************************************************************

// $801c00/$801c02 hold the longword an outbound transfer is presenting, $801c02 the
// half at m_fifo_out_pos and $801c00 the one after it. With no NuBus target the MPU
// steps the transfer itself, reading the pair and then advancing the FIFO through
// $450000; the count runs down one per longword and raises DMAINT at zero. Outside
// such a transfer both addresses read back as plain registers.
u16 explorer_nupi_device::read_801c00_port(u16 half, u16 readback)
{
	if (m_dma_mode != DMA_FIFO_TO_MPU)
		return readback;

	u16 const data = m_fifo[(m_fifo_out_pos + half) & 0x7ff];
	if (half && !--m_dma_count)
		dma_transfer_complete();
	return data;
}

void explorer_nupi_device::mpu_map(address_map &map)
{
	map.unmap_value_high();

	map(0x000000, 0x003fff).rom().region("firmware", 0);
	map(0x040000, 0x043fff).rom().region("firmware", 0);

	map(0x180000, 0x180fff).ram().share("ram");

	// Write-only?
	map(0x080180, 0x080181).lrw16(NAME([this]() {
		LOGMASKED(LOG_MISC, "%s: RD 80180\n", machine().describe_context());
		return 0;
	}), NAME([this](u16 data) {
		if (m_dma_transfer_start_pending)
			m_fifo_in_pos = data & 0x0fff;
		m_fifo_out_pos = data & 0x07ff;
	}));
	map(0x080190, 0x080191).lrw16(NAME([this]() {
		LOGMASKED(LOG_MISC, "%s: RD 80190\n", machine().describe_context());
		return 0;
	}), NAME([this](u16 data) {
		m_unknown_518000 = data & 0x0fff;
	}));
	map(0x0801a2, 0x0801a2).lrw8(NAME([this]() {
		LOGMASKED(LOG_MISC, "%s: RD 801a2\n", machine().describe_context());
		return 0;
	}), NAME([this](u8 data) {
		LOGMASKED(LOG_MISC, "%s: WR 801a2 = %02x\n", machine().describe_context(), data);
		if (data)
			m_flag_register &= ~FLAG_SELF_TEST_PASSED;
		else
			m_flag_register |= FLAG_SELF_TEST_PASSED;
		update_leds();
	}));
	map(0x0801a4, 0x0801a4).lrw8(NAME([this]() {
		LOGMASKED(LOG_MISC, "%s: RD 801a4\n", machine().describe_context());
		return 0;
	}), NAME([this](u8 data) {
		LOGMASKED(LOG_MISC, "%s: WR 801a4 = %02x\n", machine().describe_context(), data);
		m_unknown_280001_bits12_toggle = !data;
	}));
	// Unknown
	map(0x0801a6, 0x0801a6).lrw8(NAME([this]() {
		LOGMASKED(LOG_MISC, "%s: RD 801a6\n", machine().describe_context());
		return 0;
	}), NAME([this](u8 data) {
		LOGMASKED(LOG_MISC, "%s: WR 801a6 = %02x\n", machine().describe_context(), data);
	}));
	// Transfer direction (0 = FIFO to memory, 0xff = memory to FIFO).
	map(0x0801a8, 0x0801a8).lrw8(NAME([this]() {
		LOGMASKED(LOG_MISC, "%s: RD 801a8\n", machine().describe_context());
		return 0;
	}), NAME([this](u8 data) {
		LOGMASKED(LOG_MISC, "%s: WR 801a8 = %02x\n", machine().describe_context(), data);
		m_dma_direction = data;
	}));
	// The real "go" strobe for a DMA transfer.
	map(0x0801aa, 0x0801aa).lrw8(NAME([this]() {
		LOGMASKED(LOG_MISC, "%s: RD 801aa\n", machine().describe_context());
		return 0;
	}), NAME([this](u8 data) {
		LOGMASKED(LOG_MISC, "%s: WR 801aa = %02x\n", machine().describe_context(), data);
		if (data == 0xff && m_dma_count)
		{
			m_dma_in_flight = true;
			m_dma_out_byte_phase = 0;

			bool const real_transfer = m_dma_target_configured;
			m_dma_target_configured = false;

			// One engine, sharing the address and count registers, so the strobe picks a
			// single transfer for them to drive.
			if (real_transfer)
				m_dma_mode = (m_dma_direction != 0) ? DMA_NUBUS_TO_SCSI : DMA_FIFO_TO_NUBUS;
			else if (m_dma_address_loaded)
				m_dma_mode = DMA_ONBOARD;
			else
				m_dma_mode = (m_dma_direction != 0) ? DMA_FIFO_DISCARD : DMA_FIFO_TO_MPU;

			if (dma_draining())
			{
				m_fifo_drain_pos = m_dma_transfer_start_pos;
				dma_drain_kick();
			}

			if (m_dma_mode == DMA_ONBOARD)
			{
				LOGMASKED(LOG_DMA, "%s: on-board dma armed addr=%05x %s %u-bit count=%u\n", machine().describe_context(),
						u32(m_dma_address_lo_raw) << 2, m_dma_direction ? "mem->fifo" : "fifo->mem",
						BIT(m_dma_address_hi_raw, 15) ? 16 : 32, m_dma_count);
				onboard_dma_run();
			}
			else
			{
				m_dma_irq5_enabled = false;
			}
		}
		else
		{
			m_dma_irq5_enabled = false;
		}
		m_dma_address_loaded = false;
	}));
	// Unknown
	map(0x0801ab, 0x0801ab).lrw8(NAME([this]() {
		LOGMASKED(LOG_MISC, "%s: RD 801ab\n", machine().describe_context());
		return 0;
	}), NAME([this](u8 data) {
		LOGMASKED(LOG_MISC, "%s: WR 801ab = %02x\n", machine().describe_context(), data);
	}));
	map(0x0801ac, 0x0801ac).lrw8(NAME([this]() {
		LOGMASKED(LOG_MISC, "%s: RD 801ac\n", machine().describe_context());
		return 0;
	}), NAME([this](u8 data) {
		LOGMASKED(LOG_MISC, "%s: WR 801ac = %02x\n", machine().describe_context(), data);
		// Also the yellow SCSI bus fault LED.
		if (data)
			m_flag_register &= ~FLAG_SCSI_PASSED;
		else
			m_flag_register |= FLAG_SCSI_PASSED;
		update_leds();
	}));
	map(0x0801ae, 0x0801ae).lrw8(NAME([this]() {
		LOGMASKED(LOG_MISC, "%s: RD 801ae\n", machine().describe_context());
		return 0;
	}), NAME([this](u8 data) {
		LOGMASKED(LOG_MISC, "%s: WR 801ae = %02x\n", machine().describe_context(), data);
		if (data)
			m_flag_register &= ~FLAG_SELF_TEST_COMPLETE;
		else
			m_flag_register |= FLAG_SELF_TEST_COMPLETE;
	}));
	map(0x0801b0, 0x0801b1).lrw16(NAME([this]() {
		return page_register_r();
	}),	NAME([this](u16 data) {
		page_register_w(data);
	}));
	map(0x0801c0, 0x0801c1).lw16(NAME([this](u16 data) {
		m_dma_address_lo_raw = data;
		m_dma_address = (u32(m_dma_address_hi_raw) << 18) + (u32(m_dma_address_lo_raw) << 2);
		m_dma_address_loaded = true;
		m_dma_address_lo_fresh = true;
		m_dma_target_configured = true;
		LOGMASKED(LOG_DMA, "%s: WR 801c0 = %04x -> m_dma_address=%08x\n", machine().describe_context(), data, m_dma_address);
	}));
	map(0x0801d0, 0x0801d1).lw16(NAME([this](u16 data) {
		m_dma_address_hi_raw = data;
		m_dma_address = (u32(m_dma_address_hi_raw) << 18) + (u32(m_dma_address_lo_raw) << 2);
		m_dma_address_loaded = true;
		m_dma_target_configured = true;
		LOGMASKED(LOG_DMA, "%s: WR 801d0 = %04x -> m_dma_address=%08x\n", machine().describe_context(), data, m_dma_address);
	}));
	map(0x100001, 0x100001).lrw8(NAME([this]() {
		LOGMASKED(LOG_MISC, "%s: RD 100001 = %02x\n", machine().describe_context(), m_unknown_100001);
		return m_unknown_100001;
	}), NAME([this](u8 data) {
		LOGMASKED(LOG_MISC, "%s: WR 100001 = %02x\n", machine().describe_context(), data);
		m_unknown_100001 = data;

		m_dma_target_configured = false;

		if (!m_dma_count_have_pending_byte)
		{
			m_dma_count_pending_byte = data;
			m_dma_count_have_pending_byte = true;
		}
		else
		{
			u16 const descriptor = (u16(data) << 8) | m_dma_count_pending_byte;
			m_dma_count = u32(descriptor) + 2;
			LOGMASKED(LOG_DMA, "%s: 100001 descriptor complete (%02x,%02x) -> m_dma_count=%08x (32-bit NuBus words)\n", machine().describe_context(), m_dma_count_pending_byte, data, m_dma_count);
			m_dma_count_have_pending_byte = false;
		}
	}));
	// This just pleases the self test. No other uses found, unknown what is behind it.
	map(0x100005, 0x100005).lrw8(NAME([this]() {
		LOGMASKED(LOG_MISC, "%s: RD 100005 = %02x\n", machine().describe_context(), m_unknown_100005);
		return m_unknown_100005;
	}), NAME([this](u8 data) {
		u8 const previous = m_unknown_100005;
		m_unknown_100005 = data;
		if (data == 0 && previous != 0)
			m_interval_timer->adjust(attotime::from_usec(30)); // wild guess
	}));
	map(0x100007, 0x100007).lrw8(
			NAME([this]() { LOGMASKED(LOG_MISC, "%s: RD 100007\n", machine().describe_context()); return 0; }),
			NAME([this](u8 data) {
				LOGMASKED(LOG_MISC, "%s: WR 100007 = %02x\n", machine().describe_context(), data);
				m_mpu->set_input_line(M68K_IRQ_3, CLEAR_LINE);
				m_mpu->set_input_line(M68K_IRQ_1, CLEAR_LINE);
				m_dma_in_flight = false;
				m_unknown_300001 = 0x0c;
			}));
	map(0x280000, 0x280000).lr8(NAME([this]() {
		return m_unknown_280000;
	}));
	map(0x280001, 0x280001).r(FUNC(explorer_nupi_device::unknown_280001_r));
	map(0x280002, 0x280002).lr8(NAME([this]() {
		return u8(m_dma_address_lo_raw) & 0x8f;
	}));

	map(0x300000, 0x300000).lr8(NAME([this]() {
		LOGMASKED(LOG_MISC, "%s: RD 300000 = %02x\n", machine().describe_context(), m_unknown_300000);
		return m_unknown_300000;
	}));
	map(0x300001, 0x300001).lr8(NAME([this]() {
		LOGMASKED(LOG_MISC, "%s: RD 300001 = %02x\n", machine().describe_context(), m_unknown_300001);
		return m_unknown_300001;
	}));

	map(0x200000, 0x20003f).lrw8(NAME([this](offs_t offset) {
		LOGMASKED(LOG_MISC, "%s: RD 200000+%02x = %02x\n", machine().describe_context(), offset, m_interval_timer_regs[offset]);
		return m_interval_timer_regs[offset];
	}), NAME([this](offs_t offset, u8 data) {
		LOGMASKED(LOG_MISC, "%s: WR 200000+%02x = %02x\n", machine().describe_context(), offset, data);
		m_interval_timer_regs[offset] = data;
	}));

	map(0x3801e0, 0x3801e0).lrw8(NAME([this]() {
		LOGMASKED(LOG_MISC, "%s: RD 3801e0\n", machine().describe_context());
		return 0;
	}), NAME([this](u8 data) {
		LOGMASKED(LOG_MISC, "%s: WR 3801e0 = %02x\n", machine().describe_context(), data);
		m_mpu->set_input_line(M68K_IRQ_4, CLEAR_LINE);
		m_unknown_300001 = data ? 0x0c : 0x00;
	}));
	// Unknown
	map(0x3801e4, 0x3801e4).lrw8(NAME([this]() {
		LOGMASKED(LOG_MISC, "%s: RD 3801e4\n", machine().describe_context());
		return 0;
	}), NAME([this](u8 data) {
		LOGMASKED(LOG_MISC, "%s: WR 3801e4 = %02x\n", machine().describe_context(), data);
	}));
	// Unknown
	map(0x3801e6, 0x3801e6).lrw8(NAME([this]() {
		LOGMASKED(LOG_MISC, "%s: RD 3801e6\n", machine().describe_context());
		return 0;
	}), NAME([this](u8 data) {
		LOGMASKED(LOG_MISC, "%s: WR 3801e6 = %02x\n", machine().describe_context(), data);
	}));
	map(0x3801e8, 0x3801e8).lrw8(NAME([this]() {
		LOGMASKED(LOG_MISC, "%s: RD 3801e8\n", machine().describe_context());
		return 0;
	}), NAME([this](u8 data) {
		m_unknown_450000_byte_phase = 0;
	}));
	map(0x380218, 0x380218).lw8(NAME([this](u8 data) {
		LOGMASKED(LOG_MISC, "%s: WR 380218 = %02x\n", machine().describe_context(), data);
		m_unknown_300001 = 0x0c;
	}));
	// Ack IRQ5?
	map(0x3801ea, 0x3801ea).lrw8(NAME([this]() {
		LOGMASKED(LOG_MISC, "%s: RD 3801ea\n", machine().describe_context());
		return 0;
	}), NAME([this](u8 data) {
		LOGMASKED(LOG_MISC, "%s: WR 3801ea = %02x\n", machine().describe_context(), data);
		m_mpu->set_input_line(M68K_IRQ_5, CLEAR_LINE);
		m_dma_irq5_enabled = data;
	}));

	map(0x440000, 0x440001).lrw16(NAME([this]() {
		return m_unknown_450000_holding;
	}), NAME([this](u16 data) {
		fifo_push(data);
	}));
	map(0x450000, 0x450007).lr8(NAME([this]() {
		m_unknown_300001 = 0x00;
		u16 const data = m_fifo[m_fifo_out_pos];
		u8 const result = (m_unknown_450000_byte_phase & 1) ? u8(data) : u8(data >> 8);
		m_unknown_450000_byte_phase = (m_unknown_450000_byte_phase + 1) & 3;
		if (m_unknown_450000_byte_phase == 0)
		{
			m_fifo_out_pos = (m_fifo_out_pos + 1) & 0x7ff;
			onboard_dma_run(true);
		}
		return result;
	}));
	map(0x450000, 0x450001).lw8(NAME([this](offs_t offset, u8 data) {
		// The odd lane is the low byte, and writing it pushes the assembled word.
		if (offset)
		{
			m_unknown_450000_holding = (m_unknown_450000_holding & 0xff00) | data;
			// The word moving through the port is what clocks the address counters,
			// not the $3801e8 strobe: ROM 0x698 loops strobe / read both / push one
			// word, and reads back the preset on the first pass.
			fifo_push(m_unknown_450000_holding);
			m_unknown_518000++;
		}
		else
		{
			m_unknown_450000_holding = (m_unknown_450000_holding & 0x00ff) | (u16(data) << 8);
		}
	}));

	map(0x508000, 0x508001).lrw16(NAME([this]() {
		return m_fifo_in_pos;
	}), NAME([this](u16 data) {
		m_fifo_in_pos = data;
	}));
	map(0x518000, 0x518001).lrw16(NAME([this]() {
		u16 const result = m_dma_in_flight ? m_fifo_in_pos : m_unknown_518000;
		LOGMASKED(LOG_DMA, "%s: RD 518000 -> %04x (in_flight=%d, 508000=%04x, 518000=%04x)\n", machine().describe_context(), result, m_dma_in_flight, m_fifo_in_pos, m_unknown_518000);
		return result;
	}), NAME([this](u16 data) {
		LOGMASKED(LOG_DMA, "%s: WR 518000 = %04x\n", machine().describe_context(), data);
		m_unknown_518000 = data;
	}));

	map(0x568000, 0x56801f).m(m_scsi, FUNC(ncr5385_device::map)).umask16(0x00ff);

	map(0x5c8000, 0x5c8001).lrw16(NAME([this]() {
		return m_unknown_dma_803c00;
	}), NAME([this](u16 data) {
		m_unknown_dma_801c00 = data;
	}));
	map(0x5c8002, 0x5c8003).lrw16(NAME([this]() {
		return m_unknown_dma_803c00;
	}), NAME([this](u16 data) {
		m_unknown_dma_801c02 = data;
	}));
	// Genuinely unmapped: entry 3's own self-test (ROM 0x298 dispatcher, 0x4a4) reads this
	// address with D7 bit 13 set beforehand, then falls through to a check that only
	// passes if bit 13 has ALREADY been cleared by the time it re-checks it - and the
	// real bus-error vector handler (ROM 0x375e) explicitly tests that same bit and jumps
	// back into the self-test's own recovery code ($4de) when set, proving a genuine bus
	// fault is the expected outcome here, not a readable register.
	map(0xc00000, 0xc0000f).rw(m_mpu, FUNC(m68000_device::berr_r), FUNC(m68000_device::berr_w));

	map(0x801c00, 0x801c01).lr16(NAME([this]() {
		return read_801c00_port(1, m_unknown_dma_801c00);
	}));
	map(0x801c02, 0x801c03).lr16(NAME([this]() {
		return read_801c00_port(0, m_unknown_dma_801c02);
	}));

	map(0x800c00, 0x800c01).lrw16(NAME([this]() {
		LOGMASKED(LOG_DMA, "%s: dma_address hi read = %04x\n", machine().describe_context(), u16(m_dma_address >> 16));
		return u16(m_dma_address >> 16);
	}), NAME([this](u16 data) {
		m_dma_address = (m_dma_address & 0x0000ffff) | (u32(data) << 16);
		LOGMASKED(LOG_DMA, "%s: dma_address hi = %04x -> %08x\n", machine().describe_context(), data, m_dma_address);
	}));
	map(0x800c02, 0x800c03).lrw16(NAME([this]() {
		u16 data;
		if (m_dma_address_lo_fresh)
		{
			data = u16(m_dma_address);
			m_dma_address_lo_fresh = false;
			m_dma_address_lo_negate_next = false;
		}
		else
		{
			data = m_dma_address_lo_negate_next ? u16(~m_dma_address) : u16(m_dma_address);
			m_dma_address_lo_negate_next = !m_dma_address_lo_negate_next;
		}
		LOGMASKED(LOG_DMA, "%s: dma_address lo read = %04x\n", machine().describe_context(), data);
		return data;
	}), NAME([this](u16 data) {
		m_dma_address = (m_dma_address & 0xffff0000) | data;
		m_dma_address_lo_fresh = true;
		LOGMASKED(LOG_DMA, "%s: dma_address lo = %04x -> %08x\n", machine().describe_context(), data, m_dma_address);
	}));
	// Unknown
	map(0x800c04, 0x800c05).lr16(NAME([this]() {
		u16 const data = UNKNOWN_800C04_SEQUENCE[m_unknown_800c04_toggle];
		m_unknown_800c04_toggle ^= 1;
		LOGMASKED(LOG_DMA, "%s: unknown 800c04 read = %04x\n", machine().describe_context(), data);
		return data;
	}));
	map(0x802c00, 0x802c01).lrw16(NAME([this]() {
		return u16(m_page_register << 2);
	}), NAME([this](u16 data) {
		m_dma_count = (m_dma_count & 0x0000ffff) | (u32(data) << 16);
		LOGMASKED(LOG_DMA, "%s: dma_count hi = %04x -> %08x\n", machine().describe_context(), data, m_dma_count);
	}));
	map(0x802c02, 0x802c03).lrw16(NAME([this]() {
		return u16(m_dma_count);
	}), NAME([this](u16 data) {
		m_dma_count = (m_dma_count & 0xffff0000) | data;
		LOGMASKED(LOG_DMA, "%s: dma_count lo = %04x -> %08x\n", machine().describe_context(), data, m_dma_count);
	}));
	map(0x803c00, 0x803c01).lw16(NAME([this](u16 data) {
		m_unknown_dma_803c00 = data;
	}));
	// Unknown
	map(0x81adaa, 0x81adab).lr16(NAME([]() { return u16(0xada9); }));
	map(0x806e56, 0x806e57).lr16(NAME([]() { return u16(0x6e55); }));

	// NuBus access window
	map(0x880000, 0x8bffff).rw(FUNC(explorer_nupi_device::nubus_window_r), FUNC(explorer_nupi_device::nubus_window_w));
}


u16 explorer_nupi_device::page_register_r()
{
	return m_page_register;
}


void explorer_nupi_device::page_register_w(u16 data)
{
	m_page_register = data;
	LOGMASKED(LOG_MISC, "%s: page_register = %04x\n", machine().describe_context(), data);
}


u16 explorer_nupi_device::nubus_window_r(offs_t offset, u16 mem_mask)
{
	u32 const nubus_addr = (u32(m_page_register) << 18) | ((offset ^ 1) << 1);
	u16 const data = nubus().space().read_word(nubus_addr, mem_mask);
	LOGMASKED(LOG_NUBUS, "%s: nubus_window_r offset=%05x -> nubus_addr=%08x data=%04x\n", machine().describe_context(), offset, nubus_addr, data);
	return data;
}


void explorer_nupi_device::nubus_window_w(offs_t offset, u16 data, u16 mem_mask)
{
	u32 const nubus_addr = (u32(m_page_register) << 18) | ((offset ^ 1) << 1);
	LOGMASKED(LOG_NUBUS, "%s: nubus_window_w offset=%05x -> nubus_addr=%08x data=%04x\n", machine().describe_context(), offset, nubus_addr, data);
	nubus().space().write_word(nubus_addr, data, mem_mask);
}

//**************************************************************************
//  SCSI
//**************************************************************************

void explorer_nupi_device::scsi_irq_w(int state)
{
	LOGMASKED(LOG_MISC, "%s: scsi_irq_w state=%d\n", machine().describe_context(), state);
	m_mpu->set_input_line(M68K_IRQ_2, state ? ASSERT_LINE : CLEAR_LINE);
}


void explorer_nupi_device::push_fifo_word_to_nubus(u16 word)
{
	if (!m_scsi_fifo_have_pending_word)
	{
		m_scsi_fifo_pending_word = word;
		m_scsi_fifo_have_pending_word = true;
		return;
	}

	u32 const longword = swapendian_int32((u32(m_scsi_fifo_pending_word) << 16) | word);
	u32 const real_addr = m_dma_address;
	if (m_dma_mode == DMA_FIFO_TO_NUBUS)
	{
		LOGMASKED(LOG_DMA, "%s: dma -> nubus[%08x] = %08x\n", machine().describe_context(), real_addr, longword);
		nubus().space().write_dword(real_addr, longword);
	}
	else
	{
		LOGMASKED(LOG_DMA, "%s: dma (no target configured, not writing to nubus) dma_addr=%08x = %08x\n", machine().describe_context(), m_dma_address, longword);
	}
	m_dma_address += 4;
	m_scsi_fifo_have_pending_word = false;

	m_dma_count--;

	if (!m_dma_count)
		dma_transfer_complete();
}

void explorer_nupi_device::scsi_dreq_w(int state)
{
	if (!state)
		return;

	LOGMASKED(LOG_DMA, "%s: scsi_dreq_w state=%d m_dma_count=%08x\n", machine().describe_context(), state, m_dma_count);

	u32 const ctrl = m_scsibus->ctrl_r();
	bool const in = (ctrl & nscsi_device_interface::S_INP);

	if (in)
	{
		u8 const data = m_scsi->dma_r();
		if (!m_scsi_fifo_have_pending_byte)
		{
			LOGMASKED(LOG_DMA, "%s: scsi_dreq_w IN byte=%02x (pending, no word yet)\n", machine().describe_context(), data);
			m_scsi_fifo_pending_byte = data;
			m_scsi_fifo_have_pending_byte = true;
		}
		else
		{
			if (m_dma_transfer_start_pending)
			{
				m_dma_transfer_start_pos = m_fifo_in_pos & 0x7ff;
				m_dma_transfer_start_pending = false;
			}

			u16 const word = (u16(m_scsi_fifo_pending_byte) << 8) | data;
			LOGMASKED(LOG_DMA, "%s: scsi_dreq_w IN byte=%02x -> fifo[%u] = %04x\n", machine().describe_context(), data, m_fifo_in_pos & 0x7ff, word);
			fifo_push(word);
			m_scsi_fifo_have_pending_byte = false;

			dma_drain_kick();
		}
	}
	else
	{
		m_scsi->dma_w(nubus().space().read_byte(m_dma_address));
		m_dma_address++;

		if (m_dma_mode == DMA_NUBUS_TO_SCSI && ++m_dma_out_byte_phase == 4)
		{
			m_dma_out_byte_phase = 0;
			m_dma_count--;

			if (!m_dma_count)
			{
				m_mpu->set_input_line(M68K_IRQ_1, ASSERT_LINE);

				m_dma_mode = DMA_IDLE;
				m_unknown_100001 = 0;
			}
		}
	}
}


//**************************************************************************
//  Machine configuration
//**************************************************************************

void explorer_nupi_device::device_add_mconfig(machine_config &config)
{
	M68000(config, m_mpu, 40_MHz_XTAL / 4); // Image of board has a 40MHz crystal, documents mention 68000 at 10MHz.
	m_mpu->set_addrmap(AS_PROGRAM, &explorer_nupi_device::mpu_map);

	NSCSI_BUS(config, m_scsibus);
	// The unit byte in command word 0 is (unit << 3) | device, so a mass
	// storage unit's SCSI ID picks the unit numbers the software has to ask for.
	NSCSI_CONNECTOR(config, "scsibus:0", nupi_scsi_devices, "msu", false);   // units 00, 01
	NSCSI_CONNECTOR(config, "scsibus:1", nupi_scsi_devices, nullptr, false); // units 08, 09
	NSCSI_CONNECTOR(config, "scsibus:2", nupi_scsi_devices, "msu", false);   // units 10, 11
	NSCSI_CONNECTOR(config, "scsibus:3", nupi_scsi_devices, "mt3201", false); // units 18, 19

	NCR5385(config, m_scsi, 40_MHz_XTAL / 4); // clock not documented.
	m_scsibus->set_external_device(5, m_scsi);
	m_scsi->set_own_id(5);
	m_scsi->irq().set(FUNC(explorer_nupi_device::scsi_irq_w));
	m_scsi->dreq().set(FUNC(explorer_nupi_device::scsi_dreq_w));
}


//**************************************************************************
//  ROM
//**************************************************************************

ROM_START(nupi)
	ROM_REGION16_BE(0x4000, "firmware", 0)
	ROMX_LOAD("2238056-5_nupi.bin", 0x0000, 0x2000, CRC(4caf00b9) SHA1(0b96ba609e764e7052d1f26e7e242f6e89d73c9c), ROM_SKIP(1))
	ROMX_LOAD("2238057-5_nupi.bin", 0x0001, 0x2000, CRC(bb14cf27) SHA1(3b140274764ebc1ad1efbc4ed184a3d70eb84b0c), ROM_SKIP(1))

	ROM_REGION(0x4000, "firmware_nubus", ROMREGION_ERASE00)
ROM_END

const tiny_rom_entry *explorer_nupi_device::device_rom_region() const
{
	return ROM_NAME(nupi);
}
