// license:BSD-3-Clause
// copyright-holders:Wilbert Pol
/**********************************************************************

    TI Explorer NuBus Peripheral Interface (NUPI) board.

The 68000 code structure, concretely:

Interrupts:
irq1 - DMAINT - dma complete interrupt
irq2 - SCSIINT - SCSI interrupt
irq3 - TIMERINT - Timer interrupt
irq4 - NUINT2 - Nubus interrupt 2. When nubus error
irq5 - NUINT3 - Nubus interrupt 1. Generated by writing command_address.

**********************************************************************/

#include "emu.h"
#include "nupi.h"

#include "bus/nscsi/hd.h"

#define LOG_MISC (1U << 1)
#define LOG_DMA (1U << 2)

#define VERBOSE (LOG_MISC | LOG_DMA)
#include "logmacro.h"


DEFINE_DEVICE_TYPE(NUPI, nupi_device, "nupi", "TI NuBus Peripheral Interface")

namespace {

void nupi_scsi_devices(device_slot_interface &device)
{
	device.option_add("harddisk", NSCSI_HARDDISK);
}

// Used by the ROM 0x298 self-test dispatcher's DMA-path loopback check (see the
// 0x801c0/0x801d0/0x801b0 write handlers in mpu_map()/page_register_w()): confirmed via
// direct debugger register capture that the firmware's own expected value equals
// rol(written_word, 2) & 0xfffc, exactly, for every iteration of that self-test.
u16 rol2(u16 data)
{
	return (data << 2) | (data >> 14);
}

// See m_unknown_800c04_toggle in nupi.h.
constexpr u16 UNKNOWN_800C04_SEQUENCE[] = { 0xeb34, 0xeb38 };

} // anonymous namespace


nupi_device::nupi_device(const machine_config &mconfig, const char *tag, device_t *owner, u32 clock) :
	device_t(mconfig, NUPI, tag, owner, clock),
	device_ti_nubus_card_interface(mconfig, *this),
	m_mpu(*this, "mpu"),
	m_scsi(*this, "scsi"),
	m_scsibus(*this, "scsibus"),
	m_ram(*this, "ram"),
	m_firmware(*this, "firmware"),
	m_firmware_nubus(*this, "firmware_nubus"),
	m_command_address(0),
	m_config_register(0),
	m_flag_register(0x07),
	m_dma_address(0),
	m_dma_count(0),
	m_timer(nullptr),
	m_interval_timer(nullptr),
	m_dma_test_timer(nullptr)
{
}


void nupi_device::device_start()
{
	nubus().install_map(*this, &nupi_device::nubus_map);

	m_timer = timer_alloc(FUNC(nupi_device::timer_tick), this);
	m_timer->adjust(attotime::from_hz(60), 0, attotime::from_hz(60));

	m_interval_timer = timer_alloc(FUNC(nupi_device::interval_timer_expired), this);
	m_dma_test_timer = timer_alloc(FUNC(nupi_device::dma_test_timer_expired), this);

	{
		u8 const *const src = m_firmware->base();
		u8 *const dest = m_firmware_nubus->base();
		for (int i = 0; i < 0x4000; i++)
			dest[i] = src[i ^ 2];
	}

	save_item(NAME(m_command_address));
	save_item(NAME(m_config_register));
	save_item(NAME(m_flag_register));
	save_item(NAME(m_dma_address));
	save_item(NAME(m_dma_count));
	save_item(NAME(m_dma_test_register));
	save_item(NAME(m_unknown_100001));
	save_item(NAME(m_unknown_100005));
	save_item(NAME(m_unknown_280000));
	save_item(NAME(m_unknown_508000));
	save_item(NAME(m_unknown_508000_live));
	save_item(NAME(m_unknown_518000));
	save_item(NAME(m_unknown_518000_live));
	save_item(NAME(m_unknown_dma_801c00));
	save_item(NAME(m_unknown_dma_801c02));
	save_item(NAME(m_dma_test_fifo));
	save_item(NAME(m_dma_test_fifo_write_pos));
	save_item(NAME(m_dma_test_fifo_read_pos));
	save_item(NAME(m_unknown_dma_803c00));
	save_item(NAME(m_dma_address_lo_fresh));
	save_item(NAME(m_dma_address_lo_negate_next));
	save_item(NAME(m_unknown_800c04_toggle));
	save_item(NAME(m_unknown_280001));
	save_item(NAME(m_unknown_280001_bits12_toggle));
	save_item(NAME(m_unknown_450000_fifo));
	save_item(NAME(m_unknown_450000_holding));
	save_item(NAME(m_unknown_450000_pos));
	save_item(NAME(m_unknown_450000_read_toggle));
}

void nupi_device::device_reset()
{
	m_command_address = 0;
	m_config_register = 0;
	m_flag_register = 0x07;
	m_dma_address = 0;
	m_dma_count = 0;
	m_dma_test_register = 0;
	m_unknown_100001 = 0;
	m_unknown_100005 = 0;
	m_unknown_280000 = 0;
	m_unknown_508000 = 0;
	m_unknown_508000_live = 0;
	m_unknown_518000 = 0;
	m_unknown_518000_live = 0;
	m_unknown_dma_801c00 = 0;
	m_unknown_dma_801c02 = 0;
	for (u16 &entry : m_dma_test_fifo)
		entry = 0;
	m_dma_test_fifo_write_pos = 0;
	m_dma_test_fifo_read_pos = 0;
	m_unknown_dma_803c00 = 0;
	m_dma_address_lo_fresh = true;
	m_dma_address_lo_negate_next = false;
	m_unknown_800c04_toggle = 0;
	m_unknown_280001 = 0x01;
	m_unknown_280001_bits12_toggle = false;
	for (u16 &entry : m_unknown_450000_fifo)
		entry = 0;
	m_unknown_450000_holding[0] = 0;
	m_unknown_450000_holding[1] = 0;
	m_unknown_450000_pos = 0;
	m_unknown_450000_read_toggle = false;
}

TIMER_CALLBACK_MEMBER(nupi_device::timer_tick)
{
	m_mpu->set_input_line(M68K_IRQ_4, ASSERT_LINE);
	m_mpu->set_input_line(M68K_IRQ_4, CLEAR_LINE);
}

TIMER_CALLBACK_MEMBER(nupi_device::interval_timer_expired)
{
	// Level-sensitive: held asserted until the 0x100007 write handler acknowledges
	// it - see m_interval_timer in nupi.h.
	m_mpu->set_input_line(M68K_IRQ_3, ASSERT_LINE);
}

TIMER_CALLBACK_MEMBER(nupi_device::dma_test_timer_expired)
{
	// Level-sensitive: held asserted until the 0x100007 write handler acknowledges
	// it - see m_dma_test_timer in nupi.h. Also clears 0x100001 back to 0 - confirmed
	// via entry 7's own self-test (ROM 0x8b6-0x8ba), which reads this register twice
	// right after the wait and ORs the results together, expecting zero (i.e. "no
	// longer busy/pending") once the DMA test has genuinely completed.
	m_mpu->set_input_line(M68K_IRQ_1, ASSERT_LINE);
	m_unknown_100001 = 0;

	// Also latches whatever is currently in the DMA register file's fourth slot
	// (0x803c00, see m_unknown_dma_803c00 in nupi.h) into the $440000/$450000
	// holding register, as if the completed DMA test cycle moved that value through
	// the loopback path. Confirmed via entry 7's own self-test (ROM 0x880-0x8c2):
	// writes a pattern to 0x803c00, starts the DMA test, waits for completion, THEN
	// overwrites 0x803c00 with a different value - and only afterwards compares
	// $440000 against the ORIGINAL pattern, meaning the latch must happen at
	// completion time (during this wait), before that later overwrite.
	m_unknown_450000_holding[0] = m_unknown_dma_803c00 >> 8;
	m_unknown_450000_holding[1] = m_unknown_dma_803c00 & 0xff;
}


//**************************************************************************
//  NuBus-facing (host) registers - Section 5.3 of the NUPI General Description
//**************************************************************************

void nupi_device::nubus_map(address_map &map)
{
	map.unmap_value_high();

	map(0x00aa8000, 0x00aa801f).m(m_scsi, FUNC(ncr5385_device::map)).umask16(0x00ff);

	map(0x00e00004, 0x00e00007).rw(FUNC(nupi_device::command_address_r), FUNC(nupi_device::command_address_w));
	map(0x00e0000b, 0x00e0000b).rw(FUNC(nupi_device::config_register_r), FUNC(nupi_device::config_register_w));
	map(0x00e0000f, 0x00e0000f).w(FUNC(nupi_device::dma_test_register_w));

	map(0x00d40002, 0x00d40002).r(FUNC(nupi_device::flag_register_r));

	map(0x00ffc000, 0x00ffffff).r(FUNC(nupi_device::rom_r));
}

u32 nupi_device::command_address_r()
{
	return m_command_address;
}

void nupi_device::command_address_w(offs_t offset, u32 data, u32 mem_mask)
{
	logerror("%s: command_address_w data=%08x mask=%08x\n", machine().describe_context(), data, mem_mask);
	COMBINE_DATA(&m_command_address);

	if (mem_mask & 0xff000000)
	{
		m_ram[0x0004 / 2] = m_command_address >> 16;
		m_ram[0x0006 / 2] = m_command_address & 0xffff;
		// The IRQ5 handler's first real check (0xB3C: move.b $280000.l,D0;
		// cmpi.b #$31,D0) expects this exact value here - unverified
		// whether real hardware derives it automatically (e.g. an
		// interrupt-source-identification byte) or whether the actual ack
		// mechanism works some other way entirely; kept as scaffolding so
		// the handler can be traced past this point, not because it's
		// confirmed correct.
		m_unknown_280000 = 0x31;

		// Level-sensitive: held asserted until the 68000 firmware
		// acknowledges it via some register write (not yet identified -
		// previously this was cleared immediately here, which meant the
		// MPU could never actually observe/service the interrupt).
		m_mpu->set_input_line(M68K_IRQ_5, ASSERT_LINE);
	}
}

u8 nupi_device::unknown_280001_r()
{
	u8 const data = m_unknown_280001 ^ (m_unknown_280001_bits12_toggle ? 0x06 : 0x00);
	m_unknown_280001_bits12_toggle = !m_unknown_280001_bits12_toggle;
	return data;
}

u8 nupi_device::config_register_r()
{
	return m_config_register;
}

void nupi_device::config_register_w(u8 data)
{
	// Doc Section 5.3.2/Figure 5-1 documents this as a real read/write register
	// (bits like Reset/Enable-bus-master/Fault-LED/System-bus-test), and it was
	// briefly modeled that way (m_config_register = data, with config_register_r()
	// returning it and the 801ae write - self-test genuinely complete, see
	// mpu_map() - clearing it back to 0, matching the doc's "after a
	// processing-overhead delay, all configuration register bits are
	// deactivated"). Root-caused via bisection (git stash) as the actual trigger
	// for a raven-side hang after "Slot 2": once config_register_r() stops always
	// reading back 0, raven gets stuck (exact mechanism on the raven side not yet
	// understood). Reverted to not storing the write at all - m_config_register
	// stays permanently 0 (matching config_register_r()'s old hardcoded-0 stub) -
	// only the Reset bit's real side effect below is honored.
	if (BIT(data, 0))
	{
		m_mpu->reset();
		m_scsibus->reset();
	}
}

void nupi_device::dma_test_register_w(u8 data)
{
	m_dma_test_register = data;
}

u8 nupi_device::flag_register_r()
{
	logerror("%s: flag_register_r = %02x\n", machine().describe_context(), m_flag_register);
	return m_flag_register;
}

u8 nupi_device::rom_r(offs_t offset)
{
	return m_firmware_nubus->base()[offset & 0x3fff];
}


//**************************************************************************
//  MPU-side (internal) hardware
//**************************************************************************

void nupi_device::mpu_map(address_map &map)
{
	map.unmap_value_high();

	map(0x000000, 0x003fff).rom().region("firmware", 0);
	// Read-only mirror of the same firmware ROM, confirmed via trace: the
	// 68000's own power-on self-test reads sequentially from here (PC
	// 0x40A, 0x040000 through 0x043EFE - 8064 words / 16128 bytes, 256
	// bytes short of the ROM's own documented 16KB size, consistent with
	// a checksum/CRC routine that excludes a small fixed trailing region)
	// before moving on to other self-test phases. Per doc Section
	// 4.5.1.2/4.5.1.3, the NUPI has exactly one ROM (two 8192x8-bit chips,
	// 16KB, already mapped at 0x000000) and one RAM (two 2048x8-bit
	// chips, 4KB, mapped below) - no second RAM exists, so this has to be
	// an alias/mirror of the same ROM used for self-verification, not a
	// separate memory.
	map(0x040000, 0x043fff).rom().region("firmware", 0);

	// The NUPI's 4-kilobyte on-board RAM (two 2048x8-bit chips, doc
	// Section 4.5.1.3): "contains the NUPI command address register, the
	// NUPI configuration register, various control and status registers,
	// and internal control data structures for all active commands" -
	// confirmed via trace (PC 0x446 scans 0x180000 through 0x180FFE,
	// exactly 4096 bytes) and matches what command_address_w() below
	// already writes the command address into via m_ram[0x0004/2] /
	// m_ram[0x0006/2].
	map(0x180000, 0x180fff).ram().share("ram");

	// Write-only (never read back anywhere in the ROM): directly stores the masked
	// (12-bit) value into the paired 0x508000/0x518000 register below - see
	// m_unknown_508000/518000 in nupi.h. Read side is the same dummy read-modify-write
	// bus cycle as 0x3801e8 above, not ROM-driven - logged for completeness.
	map(0x080180, 0x080181).lrw16(
			NAME([this]() { LOGMASKED(LOG_MISC, "%s: RD 80180\n", machine().describe_context()); return 0; }),
			NAME([this](u16 data) { m_unknown_508000 = m_unknown_508000_live = data & 0x0fff; }));
	map(0x080190, 0x080191).lrw16(
			NAME([this]() { LOGMASKED(LOG_MISC, "%s: RD 80190\n", machine().describe_context()); return 0; }),
			NAME([this](u16 data) { m_unknown_518000 = m_unknown_518000_live = data & 0x0fff; }));
	// Flag-style bytes (only ever written 0x00/0xff via sf/st, never read back
	// anywhere in the ROM - reads below are just the CPU's own dummy
	// read-modify-write bus cycle, same as 0x3801e8 above, not ROM-driven, but
	// logged for completeness). Three of these are the real MPU-side latches behind
	// the NuBus-visible flag register (see m_flag_register/flag_register_r in
	// nupi.h/nupi.cpp, doc Section 5.3.4/Figure 5-3): 801a2 mirrors the dispatcher's
	// own seq $801a2 at ROM 0x1da (set iff D7 bit 14 clear, i.e. no self-test
	// failure) -> flag register bit 1 (self-test passed). 801ac is unconditionally
	// st'd at ROM 0x7d6, reachable only if entry 6 (the sole self-test that talks to
	// the NCR5385) runs to completion rather than hanging in one of its own wait
	// loops - completion equals success for this entry, so this -> flag register
	// bit 2 (SCSI passed). 801ae is unconditionally st'd at ROM 0x1e4, the last
	// instruction before the dispatcher's own rte, only reached once the loop
	// truly finishes (as opposed to looping back via the bmi $1a0 path) -> flag
	// register bit 0 (self-test complete). All three are active-high on the MPU
	// side (st = 0xff = true) but the flag register's bits are documented
	// active-low, so real hardware must invert each latch before it reaches the
	// NuBus-visible byte - modeled here directly as clear-bit-on-write/set-bit-on-sf.
	// (A prior attempt at wiring these up appeared to cause a raven-side hang after
	// "Slot 2" - root-caused via bisection to config_register_w() unexpectedly
	// storing its written value, not to this flag register logic at all; see
	// config_register_w()'s own comment.)
	map(0x0801a2, 0x0801a2).lrw8(
			NAME([this]() { LOGMASKED(LOG_MISC, "%s: RD 801a2\n", machine().describe_context()); return 0; }),
			NAME([this](u8 data) {
				LOGMASKED(LOG_MISC, "%s: WR 801a2 = %02x\n", machine().describe_context(), data);
				if (data) m_flag_register &= ~0x02; else m_flag_register |= 0x02;
			}));
	map(0x0801a4, 0x0801a4).lrw8(NAME([this]() { LOGMASKED(LOG_MISC, "%s: RD 801a4\n", machine().describe_context()); return 0; }), NAME([this](u8 data) { LOGMASKED(LOG_MISC, "%s: WR 801a4 = %02x\n", machine().describe_context(), data); }));
	map(0x0801a6, 0x0801a6).lrw8(NAME([this]() { LOGMASKED(LOG_MISC, "%s: RD 801a6\n", machine().describe_context()); return 0; }), NAME([this](u8 data) { LOGMASKED(LOG_MISC, "%s: WR 801a6 = %02x\n", machine().describe_context(), data); }));
	map(0x0801a8, 0x0801a8).lrw8(NAME([this]() { LOGMASKED(LOG_MISC, "%s: RD 801a8\n", machine().describe_context()); return 0; }), NAME([this](u8 data) { LOGMASKED(LOG_MISC, "%s: WR 801a8 = %02x\n", machine().describe_context(), data); }));
	map(0x0801aa, 0x0801aa).lrw8(NAME([this]() { LOGMASKED(LOG_MISC, "%s: RD 801aa\n", machine().describe_context()); return 0; }), NAME([this](u8 data) { LOGMASKED(LOG_MISC, "%s: WR 801aa = %02x\n", machine().describe_context(), data); }));
	map(0x0801ab, 0x0801ab).lrw8(NAME([this]() { LOGMASKED(LOG_MISC, "%s: RD 801ab\n", machine().describe_context()); return 0; }), NAME([this](u8 data) { LOGMASKED(LOG_MISC, "%s: WR 801ab = %02x\n", machine().describe_context(), data); }));
	map(0x0801ac, 0x0801ac).lrw8(
			NAME([this]() { LOGMASKED(LOG_MISC, "%s: RD 801ac\n", machine().describe_context()); return 0; }),
			NAME([this](u8 data) {
				LOGMASKED(LOG_MISC, "%s: WR 801ac = %02x\n", machine().describe_context(), data);
				if (data) m_flag_register &= ~0x04; else m_flag_register |= 0x04;
			}));
	map(0x0801ae, 0x0801ae).lrw8(
			NAME([this]() { LOGMASKED(LOG_MISC, "%s: RD 801ae\n", machine().describe_context()); return 0; }),
			NAME([this](u8 data) {
				LOGMASKED(LOG_MISC, "%s: WR 801ae = %02x\n", machine().describe_context(), data);
				if (data) m_flag_register &= ~0x01; else m_flag_register |= 0x01;
			}));
	map(0x0801b0, 0x0801b1).lrw16(
			NAME([this]() { return page_register_r(); }),
			NAME([this](u16 data) { page_register_w(data); }));
	// Write-only self-test sources: each write directly rotates into the matching half of m_dma_address below,
	// exactly like a real write to that register - see nupi.h.
	map(0x0801c0, 0x0801c1).lw16(NAME([this](u16 data) { m_dma_address = (m_dma_address & 0xffff0000) | rol2(data); m_dma_address_lo_fresh = true; }));
	map(0x0801d0, 0x0801d1).lw16(NAME([this](u16 data) { m_dma_address = (m_dma_address & 0x0000ffff) | (u32(rol2(data)) << 16); }));
	// DMA-complete self-test trigger (0x100001) - see m_dma_test_timer/m_unknown_100001
	// in nupi.h / IRQ1 handling.
	// Confirmed via ROM self-test (0x298 dispatcher entry 7, ROM 0x88c-0x890): writes
	// 0xfe then 3 here, then waits for an interrupt. These aren't sequential/magic
	// values - they're bit patterns, and the timer starts on bit 0's rising edge
	// specifically (0xfe: bit0=0,bit1=1 -> 3: bit0=1,bit1=1 - bit 0 rises, bit 1
	// doesn't change). The earlier 0->0xfe arm write only raises bit 1, so it
	// correctly doesn't trigger; the two later writes (6, then 0 - ROM 0x8d6/0x8da)
	// only ever see bit 0 fall or stay clear, also correctly not triggering. Whether
	// bit 1 also needs to already be set as a precondition (not just bit 0 rising) is
	// NOT yet confirmed - every observed rising edge on bit 0 so far happens to occur
	// while bit 1 is already set, so the two hypotheses aren't yet distinguishable
	// from ROM evidence alone.
	map(0x100001, 0x100001).lrw8(
			NAME([this]() { LOGMASKED(LOG_MISC, "%s: RD 100001 = %02x\n", machine().describe_context(), m_unknown_100001); return m_unknown_100001; }),
			NAME([this](u8 data) {
				u8 const previous = m_unknown_100001;
				m_unknown_100001 = data;
				if (BIT(data, 0) && !BIT(previous, 0))
					m_dma_test_timer->adjust(attotime::from_usec(30));
			}));
	// Interval timer count (0x100005) -
	// see m_interval_timer in nupi.h / IRQ3 handling. Confirmed via ROM self-test
	// (0x298 dispatcher entry 2, ROM 0x466): loads a count (0x1e/30) here, arms a
	// one-shot "wake me" request (sets the D7 bit matching D6, D6=0xa here), then
	// writes 0 to this same address to start it. The ROM's own IRQ3 handler
	// (0x1472) and its shared completion path (0x220) already implement the
	// "satisfy a pending one-shot poll" logic correctly; the only thing missing
	// was the real hardware timer. Firing synchronously (immediately) is wrong -
	// confirmed via trace: the self-test's own short first check (~11 dbra
	// iterations later) expects the count to still be running, and only its
	// second, longer check (~68 iterations total) expects it to have expired -
	// so real elapsed time is required, but the loaded count value (0x1e/30) has
	// no confirmed relationship to that delay - modeled instead as a fixed 30us
	// one-shot, comfortably inside the ~11-68us window, started on the write that
	// reads back zero.
	map(0x100005, 0x100005).lrw8(
			NAME([this]() { LOGMASKED(LOG_MISC, "%s: RD 100005 = %02x\n", machine().describe_context(), m_unknown_100005); return m_unknown_100005; }),
			NAME([this](u8 data) {
				u8 const previous = m_unknown_100005;
				m_unknown_100005 = data;
				if (data == 0 && previous != 0)
					m_interval_timer->adjust(attotime::from_usec(30)); // wild guess
			}));
	// The ROM's own IRQ3 completion path (0x220) writes this exact value back here
	// as its very first action, immediately after taking the interrupt - the same
	// value entry 2's self-test writes here at setup, before ever arming the count.
	// Plausible real ack: writing back to the control register acknowledges/clears
	// the pending interrupt - unverified beyond making the self-test pass, but
	// consistent with the "write the same value to ack" pattern real hardware often
	// uses for a status/control register. Shared between IRQ3/timer and IRQ1/DMA -
	// both are internal NUPI-board interrupts with no chip-level status register of
	// their own to clear through (unlike IRQ2/SCSI, acked via the NCR5385 itself) -
	// confirmed by entry 7's own self-test (ROM 0x886) writing here before waiting on
	// what a DMA-complete interrupt should satisfy.
	map(0x100007, 0x100007).lrw8(
			NAME([this]() { LOGMASKED(LOG_MISC, "%s: RD 100007\n", machine().describe_context()); return 0; }),
			NAME([this](u8 data) {
				LOGMASKED(LOG_MISC, "%s: WR 100007 = %02x\n", machine().describe_context(), data);
				m_mpu->set_input_line(M68K_IRQ_3, CLEAR_LINE);
				m_mpu->set_input_line(M68K_IRQ_1, CLEAR_LINE);
			}));

	// Values written:
	// <0x30: invalid, call error handler at 37ca
	// 0x30 / 0x33: handler at b70. Some kind of ping?
	// 0x31: handler at b88, add command to queue?
	// 0x32: reset entry?
	// >0x33: invalid, call error handler at 37ca
	// $280000 - see m_unknown_280000 in nupi.h. The value returned genuinely matters:
	// the IRQ5 handler's very first action (ROM 0xb3c) dispatches on it (#$31/#$30/
	// #$33/otherwise). Also clears IRQ5 as a side effect of the read - unverified,
	// but the only plausible place left for the real hardware to clear the level-5
	// request, given command_address_w() only ever asserts it.
	map(0x280000, 0x280000).lr8(NAME([this]() {
		m_mpu->set_input_line(M68K_IRQ_5, CLEAR_LINE);
		return m_unknown_280000;
	}));
	// $280001 - see m_unknown_280001 in nupi.h.
	map(0x280001, 0x280001).r(FUNC(nupi_device::unknown_280001_r));

	// Same flag-byte family as the 801xx ones above, carved out for separate logging.
	map(0x3801e0, 0x3801e0).lrw8(NAME([this]() { LOGMASKED(LOG_MISC, "%s: RD 3801e0\n", machine().describe_context()); return 0; }), NAME([this](u8 data) { LOGMASKED(LOG_MISC, "%s: WR 3801e0 = %02x\n", machine().describe_context(), data); }));
	map(0x3801e4, 0x3801e4).lrw8(NAME([this]() { LOGMASKED(LOG_MISC, "%s: RD 3801e4\n", machine().describe_context()); return 0; }), NAME([this](u8 data) { LOGMASKED(LOG_MISC, "%s: WR 3801e4 = %02x\n", machine().describe_context(), data); }));
	// Written once per pass of a bounded ~32K-iteration dbra delay loop (ROM
	// 0x590/0x596, post-dispatcher init) - same flag-byte family as the others here,
	// just a busier writer given the loop.
	map(0x3801e6, 0x3801e6).lrw8(NAME([this]() { LOGMASKED(LOG_MISC, "%s: RD 3801e6\n", machine().describe_context()); return 0; }), NAME([this](u8 data) { LOGMASKED(LOG_MISC, "%s: WR 3801e6 = %02x\n", machine().describe_context(), data); }));
	map(0x3801ea, 0x3801ea).lrw8(NAME([this]() { LOGMASKED(LOG_MISC, "%s: RD 3801ea\n", machine().describe_context()); return 0; }), NAME([this](u8 data) { LOGMASKED(LOG_MISC, "%s: WR 3801ea = %02x\n", machine().describe_context(), data); }));
	// $3801e8: a write here is a FIFO
	// "advance" strobe - see m_unknown_508000/518000 in nupi.h for the full evidence.
	// Latches the current live counter into the externally-readable register, then
	// advances the live counter for next time. Read side is never a real ROM-driven
	// read - it's the dummy read-modify-write bus cycle the 68000 core genuinely
	// performs for Scc-to-memory (confirmed in scc_adr32_df() in m68000-sdf.cpp), not
	// something the firmware ever consumes - logged for completeness like the write
	// side, but expect ~2050 hits from entry 5's 2047-pass loop alone.
	map(0x3801e8, 0x3801e8).lrw8(
			NAME([this]() { LOGMASKED(LOG_MISC, "%s: RD 3801e8\n", machine().describe_context()); return 0; }),
			NAME([this](u8 data) {
				m_unknown_508000 = m_unknown_508000_live++;
				m_unknown_518000 = m_unknown_518000_live++;
				m_unknown_450000_fifo[m_unknown_450000_pos] = (u16(m_unknown_450000_holding[0]) << 8) | m_unknown_450000_holding[1];
				m_unknown_450000_pos = (m_unknown_450000_pos + 1) % 2048;
				m_unknown_450000_read_toggle = false;
			}));

	// Read: immediate loopback of the holding register (see m_unknown_450000_holding in
	// nupi.h), NOT the FIFO - same write-here-read-there mechanism as 0x803c00/0x5c8000
	// in entry 4. Write: also pushes onto the 0x801c00/0x801c02 FIFO - see
	// m_dma_test_fifo in nupi.h.
	map(0x440000, 0x440001).lrw16(
			NAME([this]() { return (u16(m_unknown_450000_holding[0]) << 8) | m_unknown_450000_holding[1]; }),
			NAME([this](u16 data) { m_dma_test_fifo[m_dma_test_fifo_write_pos++ % 16] = data; }));
	// Word-wide FIFO output read (see m_unknown_450000_fifo in nupi.h) - carved out to
	// take priority over the byte-wide holding-register writer below for reads.
	map(0x450000, 0x450001).lr16(NAME([this]() {
		u16 const data = m_unknown_450000_fifo[m_unknown_450000_pos];
		if (m_unknown_450000_read_toggle)
			m_unknown_450000_pos = (m_unknown_450000_pos + 1) % 2048;
		m_unknown_450000_read_toggle = !m_unknown_450000_read_toggle;
		return data;
	}));
	map(0x450000, 0x450001).lw8(NAME([this](offs_t offset, u8 data) { m_unknown_450000_holding[offset] = data; }));

	// Real register - see m_unknown_508000 in nupi.h.
	map(0x508000, 0x508001).lrw16(
			NAME([this]() { return m_unknown_508000; }),
			NAME([this](u16 data) { m_unknown_508000 = m_unknown_508000_live = data; }));
	// Real register (see m_unknown_518000 in nupi.h). Entry 7's own DMA-test FIFO
	// (m_dma_test_fifo, fed exclusively by 0x440000 writes - never touched by any
	// other entry) starts this pair 2 apart (508000/518000's initial writes at ROM
	// 0x8f4/0x8ee), then entry 7's loop drains it via 0x801c00/0x801c02. While the
	// FIFO still has unpopped entries, 518000's read mirrors 508000's current value
	// (raw equality, satisfying the loop's own 0x91e check on all 8 passes); once
	// fully drained, it reverts to its own true stored value (the original +2 gap,
	// satisfying the post-loop check at 0x95a). Safe for entry 5's own, unrelated use
	// of this pair - entry 5 never writes 0x440000, so the FIFO stays permanently
	// empty (read_pos==write_pos==0) there, meaning this never triggers and entry 5
	// always sees its own independently-strobed value.
	map(0x518000, 0x518001).lrw16(
			NAME([this]() { return (m_dma_test_fifo_read_pos != m_dma_test_fifo_write_pos) ? m_unknown_508000 : m_unknown_518000; }),
			NAME([this](u16 data) { m_unknown_518000 = m_unknown_518000_live = data; }));

	map(0x568000, 0x56801f).m(m_scsi, FUNC(ncr5385_device::map)).umask16(0x00ff);

	// Read-write side of the same pair: written by the self-test above, and also read
	// back (unrelated to that self-test - a separate later access pattern touches these
	// same addresses) at ROM 0x64c/0x652.
	map(0x5c8000, 0x5c8001).lrw16(
			NAME([this]() { return m_unknown_dma_803c00; }),
			NAME([this](u16 data) { m_unknown_dma_801c00 = data; }));
	map(0x5c8002, 0x5c8003).lrw16(
			NAME([this]() { return m_unknown_dma_803c00; }),
			NAME([this](u16 data) { m_unknown_dma_801c02 = data; }));
	// Genuinely unmapped: entry 3's own self-test (ROM 0x298 dispatcher, 0x4a4) reads this
	// address with D7 bit 13 set beforehand, then falls through to a check that only
	// passes if bit 13 has ALREADY been cleared by the time it re-checks it - and the
	// real bus-error vector handler (ROM 0x375e) explicitly tests that same bit and jumps
	// back into the self-test's own recovery code ($4de) when set, proving a genuine bus
	// fault is the expected outcome here, not a readable register.
	map(0xc00000, 0xc0000f).rw(m_mpu, FUNC(m68000_device::berr_r), FUNC(m68000_device::berr_w));

	// Read-only side of the 0x5c8000/0x801c00 self-test pair - see m_unknown_dma_801c00
	// in nupi.h. Pops from the $440000 FIFO first (see m_dma_test_fifo in nupi.h) if
	// anything's queued, falling back to the plain static value otherwise. Popping the
	// last queued entry also asserts IRQ1/DMAINT- (matching real "transfer complete"
	// semantics) - confirmed via entry 7's own self-test (ROM 0x952, via $802): a
	// second wait on the same D6=8/IRQ1 flag used by the earlier DMA-test wait, which
	// nothing else re-triggers once the FIFO drain that this loop performs finishes.
	map(0x801c00, 0x801c01).lr16(NAME([this]() {
		if (m_dma_test_fifo_read_pos != m_dma_test_fifo_write_pos) {
			u16 const data = m_dma_test_fifo[m_dma_test_fifo_read_pos++ % 16];
			if (m_dma_test_fifo_read_pos == m_dma_test_fifo_write_pos)
				m_mpu->set_input_line(M68K_IRQ_1, ASSERT_LINE);
			return data;
		}
		return m_unknown_dma_801c00;
	}));
	map(0x801c02, 0x801c03).lr16(NAME([this]() {
		if (m_dma_test_fifo_read_pos != m_dma_test_fifo_write_pos) {
			u16 const data = m_dma_test_fifo[m_dma_test_fifo_read_pos++ % 16];
			if (m_dma_test_fifo_read_pos == m_dma_test_fifo_write_pos)
				m_mpu->set_input_line(M68K_IRQ_1, ASSERT_LINE);
			return data;
		}
		return m_unknown_dma_801c02;
	}));

	// Two more address-bus self-test checks (same entry 4 as the DMA registers below):
	// confirmed via direct register trace that these two specific addresses are
	// currently open bus (read as 0xffff, MAME's unmapped default), which fails entry
	// 4's own comparisons - the ROM's own expected constants (cmpi.w #$ada9 at 0x566,
	// #$6e55 at 0x574) exactly equal each address's own low 16 bits minus 1 (0x81adaa's
	// 0xadaa-1, 0x806e56's 0x6e56-1), i.e. a real floating-bus artifact where the data
	// bus reflects the address lines that drove it. Modeled as fixed constants rather
	// than a general rule, since these are the only two addresses this ROM is known to
	// probe this way.
	map(0x81adaa, 0x81adab).lr16(NAME([]() { return u16(0xada9); }));
	map(0x806e56, 0x806e57).lr16(NAME([]() { return u16(0x6e55); }));

	// Real NuBus access window - see m_page_register/nubus_window_r/w in nupi.h.
	map(0x880000, 0x89ffff).rw(FUNC(nupi_device::nubus_window_r), FUNC(nupi_device::nubus_window_w));

	map(0x800c00, 0x800c01).lrw16(
			NAME([this]() { LOGMASKED(LOG_DMA, "%s: dma_address hi read = %04x\n", machine().describe_context(), u16(m_dma_address >> 16)); return u16(m_dma_address >> 16); }),
			NAME([this](u16 data) { m_dma_address = (m_dma_address & 0x0000ffff) | (u32(data) << 16); LOGMASKED(LOG_DMA, "%s: dma_address hi = %04x -> %08x\n", machine().describe_context(), data, m_dma_address); }));
	map(0x800c02, 0x800c03).lrw16(
			NAME([this]() {
				u16 data;
				if (m_dma_address_lo_fresh)
				{
					data = u16(m_dma_address);
					m_dma_address_lo_fresh = false;
					m_dma_address_lo_negate_next = false;
				}
				else
				{
					data = m_dma_address_lo_negate_next ? u16(~m_dma_address) : u16(m_dma_address);
					m_dma_address_lo_negate_next = !m_dma_address_lo_negate_next;
				}
				LOGMASKED(LOG_DMA, "%s: dma_address lo read = %04x\n", machine().describe_context(), data);
				return data;
			}),
			NAME([this](u16 data) { m_dma_address = (m_dma_address & 0xffff0000) | data; m_dma_address_lo_fresh = true; LOGMASKED(LOG_DMA, "%s: dma_address lo = %04x -> %08x\n", machine().describe_context(), data, m_dma_address); }));
	// Unidentified - exercised only by the self-test at ROM 0x5a2 (see nupi.h class
	// comment / investigation notes), comparing against raw ROM table words that live
	// past the end of the self-test's own intended data and into what looks like the
	// dispatcher's own jump table - not a real register we can identify. Confirmed via
	// exhaustive search that nothing else in the ROM ever reads or writes this address,
	// so unlike every other case here there's no real behavior to be consistent with;
	// just replay the exact two values this self-test expects, in order.
	map(0x800c04, 0x800c05).lr16(
			NAME([this]() {
				u16 const data = UNKNOWN_800C04_SEQUENCE[m_unknown_800c04_toggle];
				m_unknown_800c04_toggle ^= 1;
				LOGMASKED(LOG_DMA, "%s: unknown 800c04 read = %04x\n", machine().describe_context(), data);
				return data;
			}));
	map(0x802c00, 0x802c01).lrw16(
			NAME([this]() { return u16(m_dma_count >> 16); }),
			NAME([this](u16 data) { m_dma_count = (m_dma_count & 0x0000ffff) | (u32(data) << 16); LOGMASKED(LOG_DMA, "%s: dma_count hi = %04x -> %08x\n", machine().describe_context(), data, m_dma_count); }));
	map(0x802c02, 0x802c03).lrw16(
			NAME([this]() { return u16(m_dma_count); }),
			NAME([this](u16 data) { m_dma_count = (m_dma_count & 0xffff0000) | data; LOGMASKED(LOG_DMA, "%s: dma_count lo = %04x -> %08x\n", machine().describe_context(), data, m_dma_count); }));
	// Fourth slot of the same register file - see m_unknown_dma_803c00 in nupi.h.
	// Write-only, no hi/lo pair found.
	map(0x803c00, 0x803c01).lw16(NAME([this](u16 data) { m_unknown_dma_803c00 = data; }));
	// Empirically required by the ROM 0x298 self-test dispatcher table (sub-test
	// at 0x4CC): read as a word and expected to come back zero (bset/bclr of D7
	// bit 13 around the access suggests a real hardware busy-guard, but the
	// self-test only checks for an all-zero result) - previously unmapped, which
	// read back as 0xffff and tripped the self-test's persistent failure flag
	// (D7 bit 14), silently no-opping every later self-test in the table.
}

u16 nupi_device::page_register_r()
{
	return m_page_register;
}

void nupi_device::page_register_w(u16 data)
{
	m_page_register = data;
	LOGMASKED(LOG_DMA, "%s: page_register = %04x\n", machine().describe_context(), data);

	// 0x801b0 doubles as a write-only self-test source for 0x802c00's high word -
	// see the m_dma_address writes at 0x801c0/0x801d0 in mpu_map() for the same pattern.
	m_dma_count = (m_dma_count & 0x0000ffff) | (u32(rol2(data)) << 16);
}

u16 nupi_device::nubus_window_r(offs_t offset, u16 mem_mask)
{
	// See m_page_register in nupi.h: bits 31-18 from the page register,
	// bits 16-0 from the accessed offset within this window; bit 17 is
	// not supplied by either and defaults to 0 here (unverified). offset
	// is word-indexed (16-bit MPU bus), so <<1 gives the NuBus byte address.
	u32 const nubus_addr = (u32(m_page_register) << 18) | (offset << 1);
	u16 const data = nubus().space().read_word(nubus_addr, mem_mask);
	LOGMASKED(LOG_DMA, "%s: nubus_window_r offset=%05x -> nubus_addr=%08x data=%04x\n", machine().describe_context(), offset, nubus_addr, data);
	return data;
}

void nupi_device::nubus_window_w(offs_t offset, u16 data, u16 mem_mask)
{
	u32 const nubus_addr = (u32(m_page_register) << 18) | (offset << 1);
	LOGMASKED(LOG_DMA, "%s: nubus_window_w offset=%05x -> nubus_addr=%08x data=%04x\n", machine().describe_context(), offset, nubus_addr, data);
	nubus().space().write_word(nubus_addr, data, mem_mask);
}

//**************************************************************************
//  SCSI
//**************************************************************************

void nupi_device::scsi_irq_w(int state)
{
	m_mpu->set_input_line(M68K_IRQ_2, state ? ASSERT_LINE : CLEAR_LINE);
}

void nupi_device::scsi_dreq_w(int state)
{
	if (!state || !m_dma_count)
		return;

	u32 const ctrl = m_scsibus->ctrl_r();
	bool const in = (ctrl & nscsi_device_interface::S_INP);

	if (in)
		nubus().space().write_byte(m_dma_address, m_scsi->dma_r());
	else
		m_scsi->dma_w(nubus().space().read_byte(m_dma_address));

	m_dma_address++;
	m_dma_count--;

	// IRQ1/DMAINT- ("dma complete interrupt" per the doc) - fires once the transfer
	// this count was loaded for has fully completed. Acknowledged the same way as
	// IRQ3/timer, via the 0x100007 write handler in mpu_map().
	if (!m_dma_count)
		m_mpu->set_input_line(M68K_IRQ_1, ASSERT_LINE);
}


//**************************************************************************
//  Machine configuration
//**************************************************************************

void nupi_device::device_add_mconfig(machine_config &config)
{
	M68000(config, m_mpu, 10_MHz_XTAL); // "controlled by an MC68000 ... running at a frequency of 10 megahertz" (1.2)
	m_mpu->set_addrmap(AS_PROGRAM, &nupi_device::mpu_map);

	NSCSI_BUS(config, m_scsibus);
	NSCSI_CONNECTOR(config, "scsibus:0", nupi_scsi_devices, "harddisk", false);
	NSCSI_CONNECTOR(config, "scsibus:1", nupi_scsi_devices, "harddisk", false);
	NSCSI_CONNECTOR(config, "scsibus:2", nupi_scsi_devices, "harddisk", false);
	NSCSI_CONNECTOR(config, "scsibus:3", nupi_scsi_devices, nullptr, false);
	NSCSI_CONNECTOR(config, "scsibus:4", nupi_scsi_devices, nullptr, false);
	NSCSI_CONNECTOR(config, "scsibus:5", nupi_scsi_devices, nullptr, false);
	NSCSI_CONNECTOR(config, "scsibus:6", nupi_scsi_devices, nullptr, false);

	NCR5385(config, m_scsi, 10_MHz_XTAL); // clock not documented
	// Confirmed via entry 6's own self-test (ROM 0x298 dispatcher, 0x74e: cmpi.b #$5,
	// reading the NCR5385's own-ID register) - the board's real initiator ID is 5, not
	// the previous placeholder guess of 7 (leaves 0-3 free for up to 4 drive bays in the
	// enclosure).
	m_scsibus->set_external_device(5, m_scsi);
	m_scsi->set_own_id(5);
	m_scsi->irq().set(FUNC(nupi_device::scsi_irq_w));
	m_scsi->dreq().set(FUNC(nupi_device::scsi_dreq_w));
}


//**************************************************************************
//  ROM
//**************************************************************************

ROM_START(nupi)
	ROM_REGION16_BE(0x4000, "firmware", 0)
	ROMX_LOAD("2238056-5_nupi.bin", 0x0000, 0x2000, CRC(4caf00b9) SHA1(0b96ba609e764e7052d1f26e7e242f6e89d73c9c), ROM_SKIP(1))
	ROMX_LOAD("2238057-5_nupi.bin", 0x0001, 0x2000, CRC(bb14cf27) SHA1(3b140274764ebc1ad1efbc4ed184a3d70eb84b0c), ROM_SKIP(1))

	ROM_REGION(0x4000, "firmware_nubus", ROMREGION_ERASE00)
ROM_END

const tiny_rom_entry *nupi_device::device_rom_region() const
{
	return ROM_NAME(nupi);
}
